title: Erfan Alimohammadi
description: in Persian "عرفان علی‌محمدی"

social:
  - title: Blog (in Persian)
    img: /assets/images/blog.png
    url: http://palindrome.ir
  - title: GitHub
    img: /assets/images/github.ico
    url: https://github.com/erfaniaa
  - title: Twitter
    img: /assets/images/twitter.ico
    url: https://twitter.com/erfanafre
  - title: Stack Overflow
    img: /assets/images/stack_overflow.png
    url: https://stackoverflow.com/users/2635857/erfan-alimohammadi
  - title: LinkedIn
    img: /assets/images/linkedin.jpg
    url: https://linkedin.com/in/erfan-alimohammadi

avatar: /assets/images/avatar.jpg
introduction: >
  Hi! I'm Erfan Alimohammadi.<br/>
  This is my personal web page.<br/>

projects:
  title: Open Source Projects
  github:
    - Erfaniaa/text-to-commit-history
    - Erfaniaa/codes2pdf
    - Erfaniaa/map-coloring
    - Erfaniaa/Tweeterify
    - Erfaniaa/Codeforces
    - Erfaniaa/compilers-course-project
    - Erfaniaa/Persian-OCR
  content: >
    <p>Other projects that I have contributed can be found in <a href="https://github.com/Erfaniaa">github.com/Erfaniaa</a>.</p>

links:
  title: Related Pages
  timeline:
    - "<a href='http://palindrome.ir'>Blog (in Persian)</a>"
    - "<a href='https://erfaniaa.github.io/resume.pdf'>Resume (PDF)</a>"
    - "<a href='https://linkedin.com/in/erfan-alimohammadi'>LinkedIn profile</a>"
    - "<a href='https://icpc.baylor.edu/ICPCID/0X1FK464JA9X'>ICPCID</a>"
    - "<a href='https://stackoverflow.com/users/2635857/erfan-alimohammadi'>Stack Overflow profile</a>"

google_analytics: UA-145465443-1
